export const AccountOperations = {
    CREATE: "CREATE",
    DEPOSITE: "DEPOSITE",
    WITHDRAW: "WITHDRAW",
    CLOSE: "CLOSE",
    UPDATE_STATE: "UPDATE_STATE"
}

export const ExpenseOperations = {
    ADD_CATEGORY: "ADD_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    ADD_EXPENSE: "ADD_EXPENSE",
    UPDATE_EXPENSE: "UPDATE_EXPENSE",
    DELETE_EXPENSE: "DELETE_EXPENSE",
    VIEW_EXPENSE: "VIEW_EXPENSE",
    LOAD_EXPENSES: "LOAD_EXPENSES"
}